name: Joris' Blog
description: Joris Morger
meta_description: "A blog about FP and such"

markdown: redcarpet
pygments: true
logo: ""
paginate: 15

# Details for the RSS feed generator
url:            'http://jorism.github.io/blog/'
author:         'Joris Morger (@jorisdamian)'
